### ISSUE TITLE
500 GET /api/friends 

### ISSUE THREAD

**Issue by dzizes** [dzizes/usosapi#39]
[E 160208 08:51:03 web:1524] Uncaught exception GET /api/friends (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/friends', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-US,en;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch', 'X-Requested-With': 'XMLHttpRequest', 'Host': 'localhost:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://localhost:8888/friends', 'Cookie': '_xsrf=2|407df644|1cb3d0496fcf554306053ec0d6d3b212|1454870743; USER_SECURE_COOKIE="2|1:0|10:1454917819|18:USER_SECURE_COOKIE|332:IntcImFjY2Vzc190b2tlbl9rZXlcIjogXCIzU2hZUXY4THl2Z2VYdGhLSnptSlwiLCBcInVybFwiOiBcImh0dHBzOi8vdXNvc2FwcHMudXcuZWR1LnBsL1wiLCBcIl9pZFwiOiB7XCIkb2lkXCI6IFwiNTZiNzg5OWRjNGY5ZDIwM2Q0NWVmZWNhXCJ9LCBcImFjY2Vzc190b2tlbl9zZWNyZXRcIjogXCJKd1NVeWdteUo4NVBwM2c5TGZKc0RuazQ4TWtmWVdRemc3Q2hoZDdZXCIsIFwiaWRcIjogXCIxMTI1MjEwOTU0NjU0NTA5OTg1MTdcIn0i|c6bff3fba0f0e42ffca7fa29cd132b6a29a0c468d5933154bb98828bec8081f2"'})
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\web.py", line 1401, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\web.py", line 1613, in future_complete
        f.result()
      File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "C:/Users/smolkows/PycharmProjects/usosapi/usosapi\handlers\handlers_api_friends.py", line 123, in get
        while (yield cursor.fetch_next):
      File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\gen.py", line 1008, in run
        value = future.result()
      File "C:\Python27\lib\site-packages\tornado-4.3-py2.7-win32.egg\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    OperationFailure: command SON([('aggregate', u'friends'), ('pipeline', [{'$match': {'user_id': ObjectId('56b7899dc4f9d203d45efeca')}}, {'$lookup': {'foreignField': 'id', 'as': 'users_info', 'from': 'users_info', 'localField': 'friend_id'}}]), (u'cursor', {})]) on namespace usos-test2.$cmd failed: exception: Unrecognized pipeline stage name: '$lookup'
[E 160208 08:51:03 web:1946] 500 GET /api/friends (::1) 33.00ms

**Comment by smola222** [comment]
sprawdz po wyczyszczeniu bazy - bo u mnie to dziala

**Comment by smola222** [comment]
mongo 3.2 required to run this query
