### ISSUE TITLE
namespace.update(self.ui)     TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by smola222** [dzizes/usosapi#59]
bug podczas rejestracji authentication_verify

[D 160212 15:06:06 helpers:35] file_name: usosqueue.py codeline: 19 function_name: self.crower.initial_user_crowl(users_id) took: 0:00:01.900807
[E 160212 15:06:06 web:1524] Uncaught exception GET /authentication/verify?scopes=studies%7Coffline_access&oauth_token=pvGhTEbmM5RTndTfM6vn&oauth_verifier=97243893 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/authentication/verify?scopes=studies%7Coffline_access&oauth_token=pvGhTEbmM5RTndTfM6vn&oauth_verifier=97243893', version='HTTP/1.1', remote_ip='::1', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:8888', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4', 'Dnt': '1', 'Connection': 'keep-alive', 'Cookie': 'USER_SECURE_COOKIE="2|1:0|10:1455285957|18:USER_SECURE_COOKIE|172:IntcInVybFwiOiBudWxsLCBcIl9pZFwiOiB7XCIkb2lkXCI6IFwiNTZiZGU2YzUzZDc4MjFhMWM3NTdkYzFmXCJ9LCBcInVzb3NfcGFpcmVkXCI6IGZhbHNlLCBcImlkXCI6IFwiMTA2MjA5OTkxNjUyMjE3NjIyNzk3XCJ9Ig==|206bc551ee4c0b778adc45bd355386270ce86ed6c2d78636b165d209cf85dd42"; _xsrf=2|8308435c|b4aeafef74e80578298d100c514e4d39|1455137614', 'Referer': 'http://localhost:8888/authentication/create'})
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/Library/Python/2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 1613, in future_complete
        f.result()
      File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1017, in run
        yielded = self.gen.send(value)
      File "/Users/doc/Documents/PycharmProjects/usosapi/usosapi/handlers/handlers_auth.py", line 220, in get
        self.render("main.html", **template_data)
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 699, in render
        html = self.render_string(template_name, **kwargs)
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 804, in render_string
        namespace = self.get_template_namespace()
      File "/Library/Python/2.7/site-packages/tornado/web.py", line 828, in get_template_namespace
        namespace.update(self.ui)
    TypeError: 'NoneType' object is not iterable
[I 160212 15:06:06 web:1946] 200 GET / (::1) 21.94ms

**Comment by dzizes** [comment]
jak nie chcesz działac z usosweb to zmień sobie port na usosapi na 8888

**Comment by smola222** [comment]
nie rozumiem, ale ja dziaam usosweb-server na porcie 8888?
Wojciech Smołkowski
wojciech.smolkowski@gmail.com
